# .github/workflows/main.yml
name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: mxcl/xcodebuild@v3.3
        with:
          xcode: 15.4
          platform: macOS
          platform-version: 10.13
          workspace: PerseusMeteo.xcodeproj/project.xcworkspace
          scheme: PerseusMeteo
          trust-plugins: true
          action: build # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: false # default = `false`
          configuration: release # no default, ie. `xcodebuild` decides itself
          
  unit-tests:
    name: Tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SwiftLint
        run: brew link --overwrite swiftlint || brew install swiftlint
      - name: XCTests
        uses: mxcl/xcodebuild@v3.3
        with:
          xcode: 15.4
          platform: macOS
          platform-version: 10.13
          workspace: PerseusMeteo.xcodeproj/project.xcworkspace
          scheme: PerseusMeteo
          trust-plugins: true
          configuration: release
